version: "3.8"

services:
  db:
    image: postgres:13.1
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: ./api
    restart: always
    command: uwsgi --ini avc_forms/uwsgi.ini
    env_file:
      - ./api/.env
      - ./postgres/.env
    depends_on:
      - db
    volumes:
      - api_data:/tmp

  app:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - app_data:/app

  nginx:
    image: nginx:1.19.5
    restart: always
    env_file:
      - ./nginx/.env
    ports:
      - "${HOST_PORT:-8080}:${NGINX_PORT:-8080}"
    volumes:
    - api_data:/api
    - app_data:/app
    - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - api
      - app

volumes:
  pg_data:
  api_data:
  app_data:
