version: "3.8"

services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - app_data:/app

  nginx:
    ports:
      - "${HOST_PORT:-8080}:${NGINX_PORT:-8080}"
    volumes:
      - app_data:/app
    depends_on:
      - app

volumes:
  app_data:
