version: "3.8"

services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=avc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: ./api
    environment:
      - POSTGRES_DB=avc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db
