version: "3.8"

services:
  db:
    image: postgres:13.1
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: ./api
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - api_data:/api

  nginx:
    image: nginx:1.19.5
    restart: always
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
    - api_data:/api
    - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - api

volumes:
  pg_data:
  api_data:
