version: "3.8"

services:
  api:
    build: ./api
    restart: always
    command: uwsgi --ini avc_forms/uwsgi.ini
    env_file:
      - ./config.env
    depends_on:
      - db
    volumes:
      - api_data:/tmp

  app:
    build: ./app
    env_file:
      - ./config.env
    volumes:
      - app_data:/app

  db:
    image: postgres:13.1
    env_file:
      - ./config.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19.5
    restart: always
    env_file:
      - ./config.env
    ports:
      - "8080:${NGINX_PORT:-8080}"
    volumes:
      - api_data:/api
      - app_data:/app
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - api
      - app

volumes:
  pg_data:
  api_data:
  app_data:
