version: "3.8"

services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - app_data:/app

  api:
    environment:
      - DJANGO_DEBUG=0

  nginx:
    volumes:
      - app_data:/app
    depends_on:
      - app

volumes:
  app_data:
