version: "3.8"

services:
  db:
    image: postgres:13.1
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: ./api
    restart: always
    command: uwsgi --ini avc_forms/uwsgi.ini
    env_file:
      - ./api/.env
      - ./postgres/.env
    depends_on:
      - db
    volumes:
      - api_data:/tmp

  nginx:
    image: nginx:1.19.5
    restart: always
    env_file:
      - ./nginx/.env
    volumes:
    - api_data:/api
    - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - api

volumes:
  pg_data:
  api_data:
